#file: noinspection UndefinedAction,UndefinedParamsPresent

name: Gradle Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Chmod Gradle wrapper
        run: sudo chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-files
          path: build/libs/*.jar